# This is a basic workflow to help you get started with Actions

name: PowerShellTest
run-name: PSTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      containerpath: ${{ steps.docker_push.outputs.ContainerPath }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: docker_push
        run: echo "containerpath=thisisConPath" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ steps.docker_push.outputs.containerpath }}
  print:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: Print
        run: echo ${{needs.build.outputs.containerpath}}
