name: Two Jobs Sample
run-name: SampleName

on: [workflow_dispatch]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this is first job"
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this second job"
  three:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this third job"
