name: Two Jobs Sample
run-name: SampleName

on: [workflow_dispatch]
jobs:
  one:
    runs-on: ubuntu-latest
    outputs: 
       output1: ${{ steps.st2.outputs.tag }}
    
    steps:
      - id: st1
        run: echo "Test this is first job"
      - id: st2
        run: echo "tag=MyNameisTag" >> "$GITHUB_OUTPUT"
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this second job"
      - run: echo "${{ needs.one.outputs.output1 }}"
  three:
    if: ${{ always() }}
    needs: [one, two]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this third job"
