name: Two Jobs Sample
run-name: ${{ github.event }} ${{ github.run_number }}
on: [workflow_dispatch]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this is first job"
  two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this second job"
