name: Custom2JobVarsPass
run-name: TestVarsPassinSteps

on: [workflow_dispatch]
jobs:
  one:
    runs-on: ubuntu-latest
    outputs: 
       output1: ${{ steps.st2.outputs.tag }}
    steps:
      - id: st2
        run: echo "tag=MyNameisTag" >> "$GITHUB_OUTPUT"
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - env:
          tag: ${{needs.one.outputs.output1}}
      - run: echo "$tag"
       
  
