name: Two Jobs Sample
run-name: TestVarsPassinSteps

on: [workflow_dispatch]
jobs:
  one:
    runs-on: ubuntu-latest
    outputs: 
       output1: ${{ steps.st2.outputs.tag }}
    
    steps:
      - id: st2
        run: echo "tag=MyNameisTag" >> "$GITHUB_OUTPUT"
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - env:
          tag: ${{needs.one.outputs.output1}}
      - run: echo "$tag"
       
  three:
    if: ${{ always() }}
    needs: [one, two]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test this third job"
