name: Variable Passing
run-name: ${{ github.actor}} Testing Variable Outputs

on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.h1 }}
      output2: ${{ steps.step2.outputs.w1 }}
    steps:
      - id: step1
        run: echo "h1=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "w1=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
